# version: "1.0"

services:
  backend:
    build: ./Backend
    ports:
      - "9001:9001"
    networks:
      - aquesafe-net

  frontend:
    build: ./Frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - aquesafe-net

networks:
  aquesafe-net:
    external: true
