# version: "1.0"

services:
  backend:
    build: ./Backend
    ports:
      - "9001:9001"

  frontend:
    build: ./Frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend

volumes:
  logs:
  data:
