name: CI Checks

on:
  push:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Tests
        run: npm test

      - name: Check for Security Vulnerabilities
        run: npm audit --audit-level=high || echo "Audit warnings found, but continuing deployment"
